#ifndef MRG_MOUSECODES
#define MRG_MOUSECODES

#define MRG_MOUSE_BUTTON_1 0
#define MRG_MOUSE_BUTTON_2 1
#define MRG_MOUSE_BUTTON_3 2
#define MRG_MOUSE_BUTTON_4 3
#define MRG_MOUSE_BUTTON_5 4
#define MRG_MOUSE_BUTTON_6 5
#define MRG_MOUSE_BUTTON_7 6
#define MRG_MOUSE_BUTTON_8 7
#define MRG_MOUSE_BUTTON_LAST MRG_MOUSE_BUTTON_8
#define MRG_MOUSE_BUTTON_LEFT MRG_MOUSE_BUTTON_1
#define MRG_MOUSE_BUTTON_RIGHT MRG_MOUSE_BUTTON_2
#define MRG_MOUSE_BUTTON_MIDDLE MRG_MOUSE_BUTTON_3

#endif