//
// Created by Mathis Lamidey on 2021-05-08.
//

#ifndef MORRIGU_VMAINCLUDEHELPER_H
#define MORRIGU_VMAINCLUDEHELPER_H

#include "Core/Warnings.h"

DISABLE_WARNING_PUSH
DISABLE_WARNING_UNUSED_PARAMETER
DISABLE_WARNING_CONSTEXPR_IF
DISABLE_WARNING_EXPRESSION_ALWAYS_TRUE
DISABLE_WARNING_PADDING_GENERATED
#include <vk_mem_alloc.h>
DISABLE_WARNING_POP

#endif  // MORRIGU_VMAINCLUDEHELPER_H
